
import { Theme } from '@material-ui/core/styles';
import { SnackbarCloseReason } from '@material-ui/core/Snackbar';
import { CheckboxProps } from '@material-ui/core/Checkbox';
import { DialogProps } from '@material-ui/core/Dialog';

export type { Theme };
export type { SnackbarCloseReason };
export type { CheckboxProps };
export type { DialogProps };

export { makeStyles, createStyles, responsiveFontSizes, createMuiTheme, ThemeProvider } from '@material-ui/core/styles';
export { default as clsx } from 'clsx';

export { default as Dialog } from '@material-ui/core/Dialog';
export { default as DialogActions } from '@material-ui/core/DialogActions';
export { default as DialogContent } from '@material-ui/core/DialogContent';
export { default as DialogContentText } from '@material-ui/core/DialogContentText';
export { default as DialogTitle } from '@material-ui/core/DialogTitle';
export { default as Card } from '@material-ui/core/Card';
export { default as CardActions } from '@material-ui/core/CardActions';
export { default as CardContent } from '@material-ui/core/CardContent';
export { default as CardMedia } from '@material-ui/core/CardMedia';
export { default as TextField } from '@material-ui/core/TextField';
export { default as FormControlLabel } from '@material-ui/core/FormControlLabel';
export { default as Checkbox } from '@material-ui/core/Checkbox';
export { default as Avatar } from '@material-ui/core/Avatar';
export { default as Backdrop } from '@material-ui/core/Backdrop';
export { default as Button } from '@material-ui/core/Button';
export { default as Drawer } from '@material-ui/core/Drawer';
export { default as Box } from '@material-ui/core/Box';
export { default as AppBar } from '@material-ui/core/AppBar';
export { default as Toolbar } from '@material-ui/core/Toolbar';
export { default as List } from '@material-ui/core/List';
export { default as Typography } from '@material-ui/core/Typography';
export { default as Divider } from '@material-ui/core/Divider';
export { default as IconButton } from '@material-ui/core/IconButton';
export { default as Badge } from '@material-ui/core/Badge';
export { default as Container } from '@material-ui/core/Container';
export { default as Grid } from '@material-ui/core/Grid';
export { default as Paper } from '@material-ui/core/Paper';
export { default as Link } from '@material-ui/core/Link';
export { default as ListItem } from '@material-ui/core/ListItem';
export { default as ListItemIcon } from '@material-ui/core/ListItemIcon';
export { default as ListItemText } from '@material-ui/core/ListItemText';
export { default as ListSubheader } from '@material-ui/core/ListSubheader';
export { default as Fab } from '@material-ui/core/Fab';
export { default as Tooltip } from '@material-ui/core/Tooltip';
export { default as Snackbar } from '@material-ui/core/Snackbar';
export { default as InputLabel } from '@material-ui/core/InputLabel';
export { default as MenuItem } from '@material-ui/core/MenuItem';
export { default as FormHelperText } from '@material-ui/core/FormHelperText';
export { default as FormControl } from '@material-ui/core/FormControl';
export { default as Select } from '@material-ui/core/Select';
export { default as CircularProgress } from '@material-ui/core/CircularProgress';
export { default as Collapse } from '@material-ui/core/Collapse';

//  https://material-ui.com/components/material-icons/
export { default as DashboardIcon } from '@material-ui/icons/Dashboard';
export { default as ShoppingCartIcon } from '@material-ui/icons/ShoppingCart';
export { default as PeopleIcon } from '@material-ui/icons/People';
export { default as BarChartIcon } from '@material-ui/icons/BarChart';
export { default as LayersIcon } from '@material-ui/icons/Layers';
export { default as AssignmentIcon } from '@material-ui/icons/Assignment';
export { default as MenuIcon } from '@material-ui/icons/Menu';
export { default as ChevronLeftIcon } from '@material-ui/icons/ChevronLeft';
export { default as NotificationsIcon } from '@material-ui/icons/Notifications';
export { default as FileCopyIcon } from '@material-ui/icons/FileCopyOutlined';
export { default as SaveIcon } from '@material-ui/icons/Save';
export { default as PrintIcon } from '@material-ui/icons/Print';
export { default as ShareIcon } from '@material-ui/icons/Share';
export { default as FavoriteIcon } from '@material-ui/icons/Favorite';
export { default as ExitToAppIcon } from '@material-ui/icons/ExitToApp';
export { default as MenuBookIcon } from '@material-ui/icons/MenuBook';
export { default as RateReviewIcon } from '@material-ui/icons/RateReview';
export { default as LockOutlinedIcon } from '@material-ui/icons/LockOutlined';
export { default as HomeIcon } from '@material-ui/icons/Home';
export { default as CloseIcon  } from '@material-ui/icons/Close';
export { default as KeyboardBackspaceIcon } from '@material-ui/icons/KeyboardBackspace';
export { default as WifiIcon  } from '@material-ui/icons/Wifi';
export { default as TimerIcon } from '@material-ui/icons/Timer';
export { default as PersonIcon } from '@material-ui/icons/Person';
export { default as NewReleasesIcon } from '@material-ui/icons/NewReleases';
export { default as AlarmIcon } from '@material-ui/icons/Alarm';
export { default as NetworkCheckIcon } from '@material-ui/icons/NetworkCheck';
export { default as ExpandMoreIcon } from '@material-ui/icons/ExpandMore';
export { default as MoreVertIcon } from '@material-ui/icons/MoreVert';
export { default as LocationOnIcon } from '@material-ui/icons/LocationOn';
export { default as ComputerIcon } from '@material-ui/icons/Computer';